// frontend/components/signupnext.tsx
import React from 'react';
import styles from './signupnext.module.css';

const SignupNext: React.FC = () => {
  const openAddStockPopup = () => {
    // Implement the function to open the Add Stock popup
  };

  return (
    <div className={styles.signin}>
      <div className={styles.signincont}>
        <div className={styles.signinside}>
          <p className={styles.textMain}>Insert your current Holdings</p>
          <table className={styles.tableMain}>
            <thead className={styles.tableHeader}>
              <tr>
                <th>Name</th>
                <th>Quantity</th>
                <th>Current Stock Rate</th>
                <th>Total Value</th>
              </tr>
            </thead>
            <tbody></tbody>
          </table>
          <div className={styles.addStock}>
            <div className={styles.addStockButton}>
              <button
                className={styles.addstockbtn}
                id="addstockbtn"
                title="Add Stock"
                onClick={openAddStockPopup}
              >
                Add Stock
              </button>
            </div>
            <div className={styles.totalValue}>
              <p className={styles.totalValueText}>Total Value -</p>
            </div>
          </div>
          <div className={styles.confirmStock}>
            <div className={styles.confirmStockButton}>
              <button
                className={styles.confirmstockbtn}
                id="confirmstockbtn"
                title="Confirm Stock"
              >
                Confirm &gt;
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SignupNext;

// src/app/signupnext/signupnext.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-signupnext',
  standalone: true,
  imports: [],
  templateUrl: './signupnext.component.html',
  styleUrl: './signupnext.component.scss'
})
export class SignupnextComponent {

}

<div class="signin">
  <div class="signincont">
    <div class="signinside">
      <p class="text-main">Insert your current Holdings</p>
      <table class="table-main">
        <thead class="table-header">
          <tr>
            <th>Name</th>
            <th>Quantity</th>
            <th>Current Stock Rate</th>
            <th>Total Value</th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>
      <div class="add-stock">
        <div class="add-stock-button">
          <button class="addstockbtn" id="addstockbtn" title="Add Stock">
            Add Stock
          </button>
        </div>
        <div class="total-value">
          <p class="total-value-text">Total Value -</p>
        </div>
      </div>
      <div class="Confirm-stock">
        <div class="Confirm-stock-button">
          <button
            class="Confirmstockbtn"
            id="Confirmstockbtn"
            title="Confirm Stock"
          >
            Confirm >
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
