// frontend/components/signin.tsx
import React, { useState } from 'react';
import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
import { useRouter } from 'next/router';
const firebaseConfig = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
    measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);

const SignIn = () => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');
    const router = useRouter();

    const handleSignIn = async (e: { preventDefault: () => void; }) => {
        e.preventDefault();
        setLoading(true);
        setError('');

        try {
            const userCredential = await signInWithEmailAndPassword(auth, email, password);
            const user = userCredential.user;
            console.log('User:', user);
            setLoading(false);
            router.push('/dashboard'); // Redirect to dashboard after successful sign-in
        } catch (error) {
            setError((error as Error).message);
            console.error('Error:', error);
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="signin">
            <div className="signincont">
                <div className="signinside">
                    <p className="head-sign">Sign In</p>
                    <form onSubmit={handleSignIn} className="input-fields">
                        <label className="textsignin" htmlFor="email">Email-ID</label>
                        <div className="email-id-input">
                            <input
                                type="email"
                                id="email"
                                name="email"
                                placeholder="Enter your email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                required
                            />
                        </div>

                        <label className="textsignin" htmlFor="password">Password</label>
                        <div className="password-input">
                            <input
                                type="password"
                                id="password"
                                name="password"
                                placeholder="Enter your password"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                                required
                            />
                        </div>
                        <p className="create-account">
                            Don't have an account? <a href="/signup">Sign Up</a>
                        </p>
                        <button
                            className="textsignin buttontext"
                            type="submit"
                            disabled={loading}
                        >
                            {loading ? 'Signing In...' : 'Sign In'}
                        </button>
                        {error && <p style={{ color: 'red' }}>{error}</p>}
                    </form>
                </div>
            </div>
        </div>
    );
};

export default SignIn;

// frontend/src/app/signin/signin.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-signin',
  standalone: true,
  imports: [],
  templateUrl: './signin.component.html',
  styleUrls: ['./signin.component.scss'],
})
export class SigninComponent {
  signinForm: FormGroup;

  constructor(
    private fb: FormBuilder,
    private http: HttpClient,
  ) {
    this.signinForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
    });
  }

  async onSubmit() {
    if (this.signinForm.valid) {
      const { email, password } = this.signinForm.value;
      try {
        const response = await this.http
          .post('http://localhost:3000/api/login', { email, password })
          .toPromise();
        console.log('Signed in successfully', response);
      } catch (error) {
        console.error('Error signing in', error);
      }
    }
  }
}

<div class="signin">
  <div class="signincont">
    <div class="signinside">
      <p class="head-sign">Sign In</p>
      <div class="input-fields">
        <label class="textsignin" for="email">Email-ID</label>
        <div class="email-id-input">
          <input
            type="email"
            id="email"
            name="email"
            placeholder="Enter your email"
          />
        </div>

        <label class="textsignin" for="password">Password</label>
        <div class="password-input">
          <input
            type="password"
            id="password"
            name="password"
            placeholder="Enter your password"
          />
        </div>
        <p class="create-account">
          Don't have an account? <a href="/signup">Sign Up</a>
        </p>
        <button
          class="textsignin buttontext"
          type="button"
          (click)="onSubmit()"
        >
          Sign In
        </button>
      </div>
    </div>
  </div>
</div>
